import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

import s from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={s.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={s.smallContainer}>
        <p className={s.wellcomeText}>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit, asperiores adipisci odio non magnam porro dolor neque delectus recusandae molestiae perferendis pariatur quos ab, provident, reprehenderit facilis ea. Maiores, itaque?
        </p>
        <div className={s.link}>
        <Link href="/jobs" >
          VEW JOB LIST
        </Link>
        </div>        
      </div>  
    </div>
  )
}
